apiVersion: v1
kind: Pod
metadata:
  name: superset
spec:
  containers:
  - name: superset
    image: apache/superset
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: superset
  ports:
   -  port: 80
      targetPort: 80
      nodePort: 30007


